export const MENU_LOAD_DATA = 'MENU_LOAD_DATA';
export const MENU_DATA_LOADED = 'MENU_DATA_LOADED';
export const MENU_OPEN_PIZZA = 'MENU_OPEN_PIZZA';
export const MENU_CLOSE_PIZZA = 'MENU_CLOSE_PIZZA';
export const MENU_SET_FETCHING = 'MENU_SET_FETCHING';
export const MENU_SET_ERROR = 'MENU_SET_ERROR';
